# Generated by Django 2.2 on 2020-07-13 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_provider', models.CharField(max_length=20)),
                ('provider_uid', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Value of priority should be at least 0'), django.core.validators.MaxValueValidator(limit_value=2, message='Value of priority should be at most 2')])),
                ('read', models.BooleanField(default=False)),
                ('heading', models.CharField(max_length=100)),
                ('sub', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BitbucketProfile',
            fields=[
                ('baseprofilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseProfileModel')),
            ],
            bases=('profiles.baseprofilemodel',),
        ),
        migrations.CreateModel(
            name='GithubProfile',
            fields=[
                ('baseprofilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseProfileModel')),
            ],
            bases=('profiles.baseprofilemodel',),
        ),
        migrations.CreateModel(
            name='GitlabProfile',
            fields=[
                ('baseprofilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseProfileModel')),
            ],
            bases=('profiles.baseprofilemodel',),
        ),
    ]
