# Generated by Django 2.2 on 2020-12-31 08:31

import apps.profiles.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repos', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('aggregated_analysis', django.contrib.postgres.fields.jsonb.JSONField(default=apps.profiles.models.default_aggregated_analysis)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
