# Generated by Django 2.2 on 2021-01-26 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_auto_20210126_1148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseprofilemodel',
            unique_together={('user', '_provider'), ('_provider', 'provider_uid')},
        ),
    ]
