# Generated by Django 2.2 on 2021-01-27 21:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210126_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofilemodel',
            name='profile_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='repo',
            name='provider',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='repo',
            name='provider_repo_id',
            field=models.IntegerField(editable=False),
        ),
    ]
