# Generated by Django 2.2 on 2021-01-28 19:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0009_auto_20210127_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repo_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('slug', models.CharField(editable=False, max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('icon', models.URLField()),
                ('repos', models.ManyToManyField(related_name='projects', to='profiles.Repo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
