# Generated by Django 2.2 on 2021-01-30 12:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210128_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='repo_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
