# Generated by Django 2.2 on 2020-11-08 13:00

import apps.base.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('slug', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('feature_image', models.URLField()),
                ('visibility', models.CharField(choices=[('PB', 'public'), ('PR', 'private'), ('UL', 'unlisted')], default='PR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('custom_excerpt', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('excerpt', models.CharField(blank=True, max_length=255, null=True)),
                ('reading_time', models.IntegerField()),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=100, null=True)),
                ('og_description', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_image', models.URLField(blank=True, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.CharField(blank=True, max_length=512, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=models.SET(apps.base.utils.get_sentinel_user), related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='blogs.Tag')),
            ],
            options={
                'unique_together': {('author', 'slug')},
            },
        ),
    ]
