# Generated by Django 2.2 on 2020-08-11 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(default=False, verbose_name='New User'),
        ),
        migrations.CreateModel(
            name='GithubAuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='GitHub ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_auth_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
