# Generated by Django 2.2 on 2020-09-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200905_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='show_avatar',
            field=models.BooleanField(default=True, verbose_name='Display Avatar on Portfolio'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_avatar',
            field=models.BooleanField(default=True, verbose_name='Display Avatar on Portfolio'),
        ),
    ]
